### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexspeller** [ember-cli/ember-twiddle#2]
List of issues that we should solve at some point
* [x] Module imports #21
* [x] CSS - including not leaking bootstrap to demo app #21 
* [x] Nice UX
* [ ] Scss #105 
* [ ] Addon support #22
* [ ] Embed support #13 
* [x] Use ember data for Github API
* [ ] Revision history #66 
* [ ] CLI #107 
* [x] Different ember / ember data versions #38 
* [ ] XHR mocking support #62 
* [ ] Support e.g. coffeescript, emberscript, emblem #106

**Comment by alexspeller** [comment]
@joostdevries any more you can think of?

**Comment by joostdevries** [comment]
at some point adding a web based CLI would be super awesome.

@stefanpenner do you have any thoughts/additions on this?

**Comment by joostdevries** [comment]
Also added revision history support, since Gists handle that out of the box :-)

**Comment by stefanpenner** [comment]
> @stefanpenner do you have any thoughts/additions on this?

we should also find a home for it

twiddle.emberjs.com or twiddle.ember-cli.com (likely emberjs.com if we can get core buy-in)

**Comment by joostdevries** [comment]
regarding modules, http://ember-gist.joostdvrs.com uses Esperanto for that.

**Comment by joostdevries** [comment]
> twiddle.emberjs.com or twiddle.ember-cli.com (likely emberjs.com if we can get core buy-in)

:+1:

@alexspeller maybe we need to split the above items into what's needed in a first release and what can be done in updates. I'll ask someone on my team to have a look at the UX this week.

**Comment by Gaurav0** [comment]
Can we update this?

**Comment by joostdevries** [comment]
@Gaurav0 I've updated the status and created issues for the remaining items. I intend to use [milestones](https://github.com/ember-cli/ember-twiddle/milestones) to prioritize items right now.
